### ISSUE TITLE
Contacts are returned only from the default source/container

### ISSUE THREAD

**Issue by KishanBagaria** [codebytere/node-mac-contacts#3]
It's returning contacts only from the first account/source.

iCloud in my case and nothing from Google:
<img width="150" alt="" src="https://user-images.githubusercontent.com/1093313/78937113-849d3100-7acd-11ea-9c76-5d7b754c1a62.png">

Probably because `defaultContainerIdentifier` is used:
https://github.com/codebytere/node-mac-contacts/blob/81af9e9133c538b13ea706f924fe8261bfc0a39a/contacts.mm#L258-L260

Instead it should enumerate and process all containers.

**Comment by codebytere** [comment]
Closed in  3a80365. Just published 1.0.0 with both fixes!
