### ISSUE TITLE
Adding a contact crashes on MacOS 13 (Ventura) 

### ISSUE THREAD

**Issue by annie-elequin** [codebytere/node-mac-contacts#39]
Tested with both node-mac-contacts v1.6.0 and v1.5.0
Electron v20.0.0
electron-builder v22.11.4

Adding a contact works as expected on Monterey, but crashes immediately when adding a contact on Macs running Ventura 

Not sure which logs are most helpful here, but willing to gather whatever is needed. I use "electron-log" on default settings and didn't see anything in the log file (except my log saying "doing contact create operation")

Also, we have sentry, and this is the stack trace of the issue I believe was created by the crash: 
https://sentry.io/share/issue/b7bf35de2812481a9d0b662fc4e7c5c2/

**Comment by KishanBagaria** [comment]
Seems like a new macOS bug in Ventura:

https://developer.apple.com/forums/thread/718743 
https://developer.apple.com/forums/thread/718834
https://developer.apple.com/forums/thread/717846

**Comment by codebytere** [comment]
Deeply unfortunate 🙃  I'll look into whether there's a good workaround.

Does adding `com.apple.developer.contacts.notes` as an entitlement mitigate the issue @annie-elequin (or @KishanBagaria)?

**Comment by KishanBagaria** [comment]
That entitlement requires manual approval by Apple sadly. Adding the entitlement rn crashes the app on launch.

**Comment by codebytere** [comment]
rip ☠️ but thanks! i'll pursue a workaround then.

**Comment by codebytere** [comment]
Closed in 9d7d53d

**Comment by codebytere** [comment]
Released in https://www.npmjs.com/package/node-mac-contacts/v/1.6.1

**Comment by KishanBagaria** [comment]
Super glad you found this workaround! 😄

**Comment by annie-elequin** [comment]
We'll update, thanks so much @codebytere , you rock!

**Comment by annie-elequin** [comment]
@codebytere unfortunately my resident Ventura tester (my own computer in Monterey) reports that it's still crashing even though I updated to 1.6.1  :(  is there something I need to change in the way that I am creating contacts? 

https://sentry.io/share/issue/4f4b9119589a43fb9818402ce03cc01e/

**Comment by KishanBagaria** [comment]
Can confirm, 1.6.1 crashes on Ventura. Tried:

```
import nmc from 'node-mac-contacts'

const success = nmc.addNewContact({
  firstName: 'William',
  lastName: 'Grapeseed',
  nickname: 'Billy',
  birthday: '1990-09-09',
  phoneNumbers: [ '+1234567890' ],
  emailAddresses: ['billy@grapeseed.com' ]
})

console.log(`New contact was ${success ? 'saved' : 'not saved'}.`)
```

**Comment by codebytere** [comment]
urgh - i just updated to ventura so i'll keep debugging.

**Comment by KishanBagaria** [comment]
Also Console.app logs [Attempt to write notes by a pre-Fall-2022 app](https://www.google.com/search?q=%22Attempt+to+write+notes+by+a+pre-Fall-2022+app%22) when the app is killed.

**Comment by annie-elequin** [comment]
@codebytere shall we keep this issue open for tracking?
