### ISSUE TITLE
Contacts cache causes Electron apps to "quit unexpectedly" when closed.

### ISSUE THREAD

**Issue by zlshames** [codebytere/node-mac-contacts#40]
When using `v1.6.0` of this package within an Electron app, closing the app via the dock will cause the app to "quit unexpectedly", and cause a macOS popup to show to report it to Apple. Downgrading to `v1.5.0` prevents the "quit unexpectedly" popup from showing. I suspect that the memory doesn't get cleared/garbage collected and macOS thinks there was a crash.

The only function I call is `contacts.getAllContacts()`. If I don't call that function, the app closes normally. For now I can just pin the dependency to v1.5.0 and use my own cache.

@codebytere I think you added the cache because of a previous issue I ran into. Sorry about causing another issue... happy holidays! ;)

**Note**: This only happens when running the app in "production" mode after building. It does not occur when running in "dev" mode via the Electron host process. It also doesn't seem to happen when running via the command line.

**Comment by jonluca** [comment]
👍🏻 - yeah any production build of electron with 1.6.0 seems to have a crash when closed via dock. Would be nice to refactor the cache, or make it optional, if that's where the exception is occuring

**Comment by codebytere** [comment]
Closed in e240ec2 - released in `v1.7.1`
