### ISSUE TITLE
Return `identifier` with contacts

### ISSUE THREAD

**Issue by KishanBagaria** [codebytere/node-mac-contacts#8]
Can you return the [identifier](https://developer.apple.com/documentation/contacts/cncontact/1403103-identifier) with all contacts?

This'll allow changing the signature of the `updateContact` and `deleteContact` methods to identify a contact by an ID instead of a name, making it less error-prone and making it possible to delete contacts that don't have a name set.

I can attempt a PR for this if you like.

**Comment by codebytere** [comment]
Sure! Why don't you go ahead and try a PR, and we'll see to proceed from there?

**Comment by codebytere** [comment]
Closed in https://github.com/codebytere/node-mac-contacts/pull/11
